server:
 port: 8085

spring:
 application:
  name: prices-service
 config:
  import: "optional:configserver:"
 datasource:
  url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  username: sa
  password: 
  driverClassName: org.h2.Driver
  datasource:
    url: jdbc:h2:file:/data/refactorizando/h2
 jpa:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
 jpa.hibernate.ddl-auto: update
  
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
